#!/usr/bin/env python
"""
Hummingbird Plot: Visualize training results from saved data.

This script loads training data generated by hummingbird_generate.py and creates
visualization plots.
"""
import matplotlib.pyplot as plt
from matplotlib import cm
import pickle
import numpy as np
import argparse
import os
import json


def parse_args():
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(description="Hummingbird Plot: Visualize optimizer training results")

    parser.add_argument("--data_file", type=str, required=True,
                       help="Path to the pickle file containing training data")
    parser.add_argument("--output_dir", type=str, default="results",
                       help="Directory to save plots")
    parser.add_argument("--output_prefix", type=str, default=None,
                       help="Prefix for output plot file (if None, uses data file basename)")
    parser.add_argument("--dpi", type=int, default=300,
                       help="DPI for saved figures")
    parser.add_argument("--figsize", type=float, nargs=2, default=[12, 8],
                       help="Figure size (width height)")
    parser.add_argument("--no_adam", action="store_true",
                       help="Don't plot Adam baseline")

    return parser.parse_args()


def load_data(data_file):
    """Load training data from pickle file.

    Args:
        data_file: Path to pickle file

    Returns:
        metadata: Dict containing all metadata
        results: Dict mapping optimizer name to training results
    """
    with open(data_file, 'rb') as f:
        data = pickle.load(f)

    return data['metadata'], data['results']


def plot_hummingbird(results, metadata, args):
    """Create the hummingbird plot.

    Args:
        results: Dict mapping optimizer name to training results
        metadata: Dict containing metadata
        args: Command line arguments
    """
    fig, ax = plt.subplots(1, 1, figsize=tuple(args.figsize))

    # Extract kappa values
    kappa_values = np.array(metadata['kappa_values'])
    optimizer = metadata['optimizer']

    # Get viridis colormap
    viridis = cm.get_cmap('viridis', len(kappa_values))

    # Plot kappa sweep curves
    for i, kappa in enumerate(kappa_values):
        opt_name = f"{optimizer}_kappa{kappa:.1f}"
        if opt_name in results:
            timestamps = results[opt_name]['timestamps']
            losses = results[opt_name]['losses']

            ax.loglog(timestamps, losses,
                     color=viridis(i),
                     alpha=0.8,
                     linewidth=2,
                     label=f'κ={kappa:.1f}')

    # Plot Adam baseline in black
    if 'adam' in results and not args.no_adam:
        timestamps = results['adam']['timestamps']
        losses = results['adam']['losses']
        ax.loglog(timestamps, losses,
                 color='black',
                 alpha=0.9,
                 linewidth=3,
                 linestyle='--',
                 label='Adam (baseline)')

    ax.set_xlabel('Training Iteration', fontsize=14)
    ax.set_ylabel('Population Risk', fontsize=14)
    ax.set_ylim(top=10)

    # Build title from metadata
    mp = metadata['model_params']
    tp = metadata['training_params']
    title = f'Hummingbird Plot: {optimizer}\n'
    title += f'α={mp["alpha"]}, m={mp["m"]}, ζ={mp["zeta"]}, d={mp["d"]}, β={mp["beta"]}\n'
    title += f'batch={tp["batch_size"]}, steps={tp["steps"]}, clipsnr={tp["clipsnr"]}, δ={tp["delta"]}'
    ax.set_title(title, fontsize=14)

    ax.grid(True, alpha=0.3)
    ax.legend(bbox_to_anchor=(1.05, 1), loc='upper left', fontsize=10)

    plt.tight_layout()

    # Determine output path
    if args.output_prefix is None:
        # Use data file basename without extension
        args.output_prefix = os.path.splitext(os.path.basename(args.data_file))[0]

    # Save plot
    os.makedirs(args.output_dir, exist_ok=True)
    filepath = os.path.join(args.output_dir, f"{args.output_prefix}.pdf")
    plt.savefig(filepath, dpi=args.dpi, bbox_inches='tight')
    print(f"Hummingbird plot saved to: {filepath}")
    plt.close()


def print_metadata(metadata):
    """Print metadata summary.

    Args:
        metadata: Dict containing metadata
    """
    print("\n" + "="*80)
    print("TRAINING DATA METADATA")
    print("="*80)
    print(f"\nTimestamp: {metadata['timestamp']}")
    print(f"Optimizer: {metadata['optimizer']}")
    print(f"Kappa values: {metadata['kappa_values']}")
    print(f"Random seed: {metadata['random_seed']}")

    print("\nModel Parameters:")
    for key, val in metadata['model_params'].items():
        print(f"  {key}: {val}")

    print("\nTraining Parameters:")
    for key, val in metadata['training_params'].items():
        print(f"  {key}: {val}")

    print("\nAdam Parameters:")
    for key, val in metadata['adam_params'].items():
        print(f"  {key}: {val}")

    if 'ademamix_params' in metadata:
        print("\nAdEMAMix Parameters:")
        for key, val in metadata['ademamix_params'].items():
            print(f"  {key}: {val}")

    print(f"\ntraceK: {metadata['traceK']:.6f}")
    print("="*80 + "\n")


def main():
    """Main function."""
    args = parse_args()

    # Check if data file exists
    if not os.path.exists(args.data_file):
        print(f"Error: Data file not found: {args.data_file}")
        return

    print(f"Loading data from: {args.data_file}")
    metadata, results = load_data(args.data_file)

    # Print metadata
    print_metadata(metadata)

    # Print results summary
    print("Training Results Summary:")
    for name, res in results.items():
        final_loss = res['losses'][-1]
        print(f"  {name}: final loss = {final_loss:.6e}")
    print()

    # Create plot
    print("Generating hummingbird plot...")
    plot_hummingbird(results, metadata, args)

    print("Done!")


if __name__ == "__main__":
    main()
